version: "3.7"

services: 
  # dbdev2dev:
  #   container_name: dbdev2dev
  #   image: mysql
  #   ports: 
  #     - 3306:3306
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: postgres
  #   volumes:
  #   - database-volume:/var/lib/mysql
            
  app:
    build: .
    container_name: api
    restart: always
    ports: 
      - 3333:3333
    volumes: 
      - .:/usr/app
    env_file: ./.env
    environment:
      - NODE_ENV=production
    # links: 
    #   - dbdev2dev
    # depends_on: 
    #   - dbdev2dev


# volumes:
#   database-volume: