version: "3.7"

services: 
  dbdev2dev:
    container_name: dbdev2dev
    image: postgres
    ports: 
      - 5432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
    - database-volume:/var/lib/postgresql'
            
  app:
    build: .
    command: npm run dev
    container_name: api
    restart: always
    ports: 
      - 3333:3333
    volumes: 
      - .:/usr/app
    links: 
      - dbdev2dev
    depends_on: 
      - dbdev2dev


volumes:
  database-volume: